# Generated by Django 5.0.6 on 2024-06-06 08:19

import django.db.models.deletion
import gebäude.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objekte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosten', models.IntegerField(validators=[gebäude.models.zusässige_negative])),
                ('einnahmen', models.IntegerField(validators=[gebäude.models.zusässige_posetive])),
                ('objekte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebäude.objekte')),
            ],
        ),
    ]
