# Generated by Django 5.0.6 on 2024-06-06 08:39

import gebäude.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosten',
            name='einnahmen',
            field=models.IntegerField(default=0, validators=[gebäude.models.zusässige_posetive]),
        ),
        migrations.AlterField(
            model_name='kosten',
            name='kosten',
            field=models.IntegerField(default=0, validators=[gebäude.models.zusässige_negative]),
        ),
    ]
