# Generated by Django 5.0.6 on 2024-06-07 07:48

import gebäude.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0002_alter_kosten_einnahmen_alter_kosten_kosten'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='von_wem',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='kosten',
            name='einnahmen',
            field=models.IntegerField(blank=True, validators=[gebäude.models.zusässige_posetive]),
        ),
        migrations.AlterField(
            model_name='kosten',
            name='kosten',
            field=models.IntegerField(blank=True, validators=[gebäude.models.zusässige_negative]),
        ),
    ]
