# Generated by Django 5.0.6 on 2024-06-07 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0003_kosten_von_wem_alter_kosten_einnahmen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='Datum',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
