# Generated by Django 5.0.6 on 2024-06-07 08:21

import django.db.models.deletion
import gebäude.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0004_kosten_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='Dokument',
            field=models.ImageField(blank=True, upload_to='dokument/'),
        ),
        migrations.CreateModel(
            name='Mietern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vornanme', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('monats_miethe', models.IntegerField(blank=True, validators=[gebäude.models.zusässige_posetive])),
                ('kaution', models.IntegerField(blank=True, validators=[gebäude.models.zusässige_posetive])),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebäude.objekte')),
            ],
        ),
        migrations.CreateModel(
            name='Technik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gegenstand', models.CharField(max_length=200)),
                ('wohnung', models.CharField(max_length=200)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gebäude.objekte')),
            ],
        ),
    ]
