# Generated by Django 5.0.6 on 2024-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0005_kosten_dokument_mietern_technik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosten',
            name='einnahmen',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='kosten',
            name='kosten',
            field=models.IntegerField(blank=True),
        ),
    ]
