# Generated by Django 5.0.6 on 2024-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0006_alter_kosten_einnahmen_alter_kosten_kosten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosten',
            name='einnahmen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kosten',
            name='kosten',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
