# Generated by Django 5.0.6 on 2024-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0007_alter_kosten_einnahmen_alter_kosten_kosten'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietern',
            name='wohnung',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
