# Generated by Django 5.0.6 on 2024-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gebäude', '0008_mietern_wohnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosten',
            name='Dokument',
            field=models.FileField(blank=True, upload_to='dokument/'),
        ),
    ]
